default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: your-username
  password: your-password
  host: localhost

development:
  <<: *default
  database: your-database_development

test:
  <<: *default
  database: your-database_test

production:
  <<: *default
  database: your-database_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>