development:
  wifi_api_key: your-wifi-api-key
  secret_password: your-secret-password


test:
  wifi_api_key: your-wifi-api-key
  secret_password: your-secret-password


production:
  wifi_api_key: <%= ENV['WIFI_API_KEY'] %>
  secret_password: <%= ENV['WIFI_API_KEY'] %>